# Generated by Django 4.0.4 on 2022-05-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='jkdfkjgdfhgj@gmail.com', max_length=55),
            preserve_default=False,
        ),
    ]
