# Generated by Django 4.0.2 on 2022-04-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('surname', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
                ('phone_number', models.CharField(max_length=55)),
                ('order_url', models.TextField()),
                ('notes', models.TextField()),
                ('order_status', models.CharField(choices=[('SE', 'Sifariş Edilmeyib'), ('SQ', 'Sifariş Qəbul edildi'), ('XAG', 'Xarici Anbara Göndərilib'), ('XA', 'Xarici Anbardadır'), ('XAGO', 'Xarici Anbardan Göndərilib'), ('GM', 'Gömrük Məntəqəsindədir'), ('DA', 'Daxili Anbardadır')], default='Sifariş Edilmeyib', max_length=4)),
            ],
        ),
    ]
